version: '3.8'

services:
  annotation_tool:
    image: annotation-tool
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./data:/app/data
    environment:
      - FLASK_ENV=development