# Deploy Next.js static site to GitHub Pages
name: Deploy Next.js site to Pages

on:
  # Trigger on push to main branch
  push:
    branches: ["main"]
  # Allow manual trigger
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18.17.0" # Use minimum required Node.js version for Next.js 14
          cache: npm

      - name: Debug root directory
        run: |
          echo "Root directory contents:"
          ls -la

      - name: Debug peritext-website directory
        run: |
          echo "Contents of peritext-website:"
          ls -la peritext-website

      - name: Install dependencies
        run: |
          cd peritext-website
          npm ci

      - name: Build and export static site
        run: |
          cd peritext-website
          npm run build
          npm run export

      - name: Debug exported files
        run: |
          echo "Listing exported files:"
          ls -la peritext-website/out

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
        with:
          path: peritext-website/out
